### ISSUE TITLE
support advanced search

### ISSUE THREAD

**Issue by twhiteaker** [twhiteaker/PASTA-JavaScript-Search-Client#3]
some sort of ‘expand’ option for advanced search to allow searching by some of the more common options, date range, author, title only, keyword only

For date range, is that date published, or datetimes within the actual data?

**Comment by scelmendorf** [comment]
My thought was date range of actual data but actually of the search parameters I suggested, I think this is probably less likely to be used than author, title, keyword because you don't necessarily know the exact dates.
Another option that might make finding stuff more user friendly after getting the results is to employ some sort of 'sortBy' box,  sort alphabetically by title, sort by latest published, sort by has most recent data? Because of the pagination it can be a lot of clicks to get the data you want if you didn't make a narrow enough search to being with.
Or, yet another option - optionally expand to display 50 per page rather than 10 to support skimming?

I really think any of these would get around my key worry = if your basic search returns 100 datasets, that's 10 additional mouseclicks to even view the last one (or some good guessing about where it lands in the order), and noone likes excessive mousing to find things.

**Comment by twhiteaker** [comment]
We need to see what sorting options PASTA provides.  

By the way, in pasta.js, there's a variable at the top named PASTA_CONFIG. Change it's "limit" value to 100 to show 100 results per page.

**Comment by scelmendorf** [comment]
yes - saw that. I think 10 is probably ok for default, but if there are complaints than I could make it default to 100. Making it dynamic based on user input is probably outside my top 10 to-do-items right now, but that would maybe be what a user would want?

**Comment by twhiteaker** [comment]
Check out these catalogs and their advanced search options
https://portal.edirepository.org/nis/advancedSearch.jsp
https://arcticdata.io/catalog/

Common minimum functionality from those two:
* search phrase
* creator
* year
    * publication year
    * collection year
* ID (DOI or local repository ID)
* taxon
* name of geographic location

ADC also supports searching by data attribute (density, length, etc).  EDI supports many other search options.

Creator seems like a good first filter to enable.

Do users really just search by keyword only? Do they only want search terms applied to the title?  I guess you'd be hunting for a specific dataset that you already suspected existed in this use case.
